version: "3.9"
services:
  postgis:
    image: "postgis/postgis"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
  geoserver:
    image: kartoza/geoserver:2.15.0
    ports:
      - 8080:8080